export var generateMobileOTP = "https://cdn-api.co-vin.in/api/v2/auth/generateMobileOTP"
export var validateMobileOtp = "https://cdn-api.co-vin.in/api/v2/auth/validateMobileOtp"
export var beneficiaries = "https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries"
export var idTypes = "https://cdn-api.co-vin.in/api/v2/registration/beneficiary/idTypes"
export var states = "https://cdn-api.co-vin.in/api/v2/admin/location/states"
export var districts = "https://cdn-api.co-vin.in/api/v2/admin/location/districts/"
export var calendarByDistrict = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?"
export var genders = "https://cdn-api.co-vin.in/api/v2/registration/beneficiary/genders"
